#!/usr/bin/python -u

import sys, getopt, dbus
from subprocess import Popen, PIPE

def main(argv):
    try:
        opts, args = getopt.getopt(argv,"h:",["help","status","play","pause",
                                              "playpause","next","prev","previous",
                                              "volumeup","volumedown"])
    except getopt.GetoptError:
        showHelp()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):             showHelp()
        elif opt == "--status":                 showCurrentSong()
        elif opt == "--play":                   perfomSpotifyAction("Play")
        elif opt == "--pause":                  perfomSpotifyAction("Pause")
        elif opt == "--playpause":              perfomSpotifyAction("PlayPause")
        elif opt == "--next":                   perfomSpotifyAction("Next")
        elif opt in ("--prev", "--previous"):   perfomSpotifyAction("Previous")
        elif opt == "--volumeup":               controlVolume("+10%")
        elif opt == "--volumedown":             controlVolume("-10%")


def showHelp():
    print ('\n  spotify-cli is a command line interface for Spotify on Linux\n\n' \
          '  usage:\n' \
          '    --help, -h\t\tshows help\n' \
          '    --status\t\tshows status (currently played song name and artist)\n' \
          '    --play\t\tplays the song\n' \
          '    --pause\t\tpauses the song\n' \
          '    --playpause\t\tplays or pauses the song (toggles a state)\n' \
          '    --next\t\tplays the next song\n' \
          '    --previous, --prev\tplays the previous song\n' \
          '    --volumeup\t\tincreases sound volume\n' \
          '    --volumedown\tdecreases sound volume\n') \

def showCurrentSong():
    try:
        session_bus = dbus.SessionBus()
        spotify_bus = session_bus.get_object("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2")
        spotify_properties = dbus.Interface(spotify_bus, "org.freedesktop.DBus.Properties")
        metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")

        # The property Metadata behaves like a python dict
        # I'm keeping this commented code for documentation purposes
        # for key, value in metadata.items():
        #   print key, value

        # print artist name and track title
        title = metadata['xesam:title'][:10] + (metadata['xesam:title'][10:] and '...')
        artist = metadata['xesam:artist'][0][:15] + (metadata['xesam:artist'][0][15:] and '...')
        print ("%s - %s") % (artist, title)
    except:
        # we go here when spotify is turned off
        print ("error: couldn't read song")

def perfomSpotifyAction(spotifyCommand):
    Popen('dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify ' \
    '/org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player."%s"' % spotifyCommand, shell=True, stdout=PIPE)

def controlVolume(volumePercent):
    Popen('pactl set-sink-volume 0 "%s"' % volumePercent, shell=True, stdout=PIPE)

if __name__ == "__main__":
    main(sys.argv[1:])
